Add support for linux x-window system.
After lots of debugging and googling, I've found that it's fun to play
with x-window.

By default, you can't open a GUI window using `xdg-open` or directly
`firefox`. `xdg-open` will show you some error like:

```
From: root@raspberrypi (Cron Daemon)
To: pi@raspberrypi
Subject: Cron <pi@raspberrypi> /usr/bin/ruby2.1 /home/pi/work/xiaohanyu/github/douban-group-dingbot/douban-group-dingbot.rb
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pi>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pi>
Message-Id: <20161106032801.6BDDE60AF8@raspberrypi>
Date: Sun,  6 Nov 2016 03:28:01 +0000 (UTC)

/usr/bin/xdg-open: 1: eval: www-browser: not found
/usr/bin/xdg-open: 1: eval: links2: not found
/usr/bin/xdg-open: 1: eval: elinks: not found
/usr/bin/xdg-open: 1: eval: links: not found
/usr/bin/xdg-open: 1: eval: lynx: not found
/usr/bin/xdg-open: 1: eval: w3m: not found
xdg-open: no method available for opening 'http://www.douban.com'
```

And I guess it means that if you running `xdg-open` without a GUI, then after you type
`xdg-open http://some-usl`, then `xdg-open` will search available CLI tools to open that
url.

However, if you use `firefox http://some-url` in a crontab script, then crontab will show you
some error like:

```
From: root@raspberrypi (Cron Daemon)
To: pi@raspberrypi
Subject: Cron <pi@raspberrypi> /usr/bin/ruby2.1 /home/pi/work/xiaohanyu/github/douban-group-dingbot/douban-group-dingbot.rb
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit
X-Cron-Env: <SHELL=/bin/sh>
X-Cron-Env: <HOME=/home/pi>
X-Cron-Env: <PATH=/usr/bin:/bin>
X-Cron-Env: <LOGNAME=pi>
Message-Id: <20161106033505.B2B4D60BF9@raspberrypi>
Date: Sun,  6 Nov 2016 03:35:05 +0000 (UTC)

Sleep 2 for a while.
Error: no display specified
Sleep 2 for a while.
Error: no display specified
```

So the problem is clear now, you must specify which `DISPLAY` you want to open a window in. You know,
X-Window is a client-server system, one client may send requests to multiple x-server. So I guess specify
a `DISPLAY` indicates which x-server that the client should sent the requests to.

Specify "DISPLAY=:0", I think, just mean that I want to open a window on the GUI system running directly
in a Linux system.